### ISSUE TITLE
JWS signature errors when running local chatbot

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#121]
I got a local chatbot installation up and running, but I noticed the following error appearing repeatedly on the console:

<details><summary>jose.exceptions.JWSSignatureError</summary>

```python
INFO:websocket-server:Reconnecting client via token: eyJhb...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/jose/jws.py", line 262, in _verify_signature
    raise JWSSignatureError()
jose.exceptions.JWSSignatureError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/jose/jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/jose/jws.py", line 73, in verify
    _verify_signature(signing_input, header, signature, key, algorithms)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/jose/jws.py", line 264, in _verify_signature
    raise JWSError("Signature verification failed.")
jose.exceptions.JWSError: Signature verification failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/hypha/utils/__init__.py", line 341, in __call__
    await self.app(scope, receive, send)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/fastapi/routing.py", line 360, in app
    await dependant.call(**values)
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/hypha/websocket.py", line 51, in websocket_endpoint
    user_info, ws, cid = parse_reconnection_token(reconnection_token)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/hypha/core/auth.py", line 344, in parse_reconnection_token
    payload = jwt.decode(
              ^^^^^^^^^^^
  File "/home/curtis/miniforge3/envs/bioimageio-chatbot/lib/python3.11/site-packages/jose/jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Signature verification failed.
```

</details>

Nonetheless, the chatbot seems to work (and is quite snappier than the default/remote version!).

**Comment by oeway** [comment]
Right, you can safely ignore this error. This is most likely because you have some browser tabs open with a previous chatbot sessions, they will try to connect server, but with an old JWT signature.

We can perhaps improve the error message to avoid confusion.

**Comment by oeway** [comment]
Closed by https://github.com/amun-ai/hypha/pull/617
