### ISSUE TITLE
`help()` in Code Interpreter throws an exception

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#128]
```python
Code Interpreter> help()
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 395, in run_async
    await coroutine
  File "<exec>", line 1, in <module>
  File "<exec>", line 183, in run
  File "<string>", line 1, in <module>
  File "<frozen _sitebuiltins>", line 103, in __call__
  File "/lib/python311.zip/pydoc.py", line 2007, in __call__
    self.interact()
  File "/lib/python311.zip/pydoc.py", line 2019, in interact
    request = self.getline('help> ')
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/pydoc.py", line 2039, in getline
    return input(prompt)
           ^^^^^^^^^^^^^
OSError: [Errno 29 I/O error
]
```

Calling the `help` function with arguments seems to work fine. It's just the no-args invocation above that is an issue.

**Comment by oeway** [comment]
I just inspected the error, it's because help try to call `input()` and that is disabled in web-worker (a thread in the browser which does not have access to UI).

For now, I will do a patch for this function.
